### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fortran-lang.org#102]
PR #100 adds a Javascript library and JSON data files - as discussed in this PR, these are best left out of the main repository. In the case of the JSON files, this is because of their file size.

Two solutions I can think of:

1) Add a shell script for cloning and updating dependencies from their respective repositories -
   script is run in CI and by contributors at checkout;

2) Use git submodules.

My preference is for submodules:

- Submodules are designed specifically for this purpose
- I don't like the idea of maintaining a shell script
- Checking-out submodules is a simpler workflow than requiring contributors to run a shell script

My impression is that the issues people face with submodules are usually when pushing commits to repositories from submodules - we won't be doing that.

**Comment by awvwgk** [comment]
Resolved with migration to the new webpage in #415
