### ISSUE TITLE
Contributor graph does not work on mobile

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#105]
The contributor graph at https://fortran-lang.org/community/ does not work on my iPhone:

![E6E4E61D-923A-47D2-9E16-151CF37915FA](https://user-images.githubusercontent.com/20568/84064732-5ed2c200-a980-11ea-999f-a2affcf8ed55.png)

I have iPhone 10 and Firefox. I also tried Safari, the same result.

**Comment by milancurcic** [comment]
FWIW, it works on Android 9 and Chrome.

**Comment by LKedward** [comment]
Thanks for the report @certik - I will look into this.
(I only tested with Android + Chrome on mobile)

**Comment by certik** [comment]
@LKedward thanks. Let me know if you want me to test something, I am happy to do that.

**Comment by LKedward** [comment]
I've been able to reproduce in the Midori web browser ([on Ubuntu](https://snapcraft.io/install/midori/ubuntu)) which I think uses the same Webkit engine as Safari.

The problem appears to be with parsing the date string from the JSON files with the Javascript Date object where some browsers implement more supported date formats in addition to the [standard format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#Date_Time_String_Format).

@certik can you test a simple fix that I'm trialling here: <https://lkedward.github.io/fortran-lang.github.io/community/>. Can you check both Safari and Firefox on your iPhone?
There may still be a few formatting issues but if it works I will open a PR.
Thanks :+1:
