### ISSUE TITLE
Quickstart tutorial: Replacing the link for Windows version of gfortran

### ISSUE THREAD

**Issue by GS76** [fortran-lang/fortran-lang.org#106]
The "Quickstart Fortran tutorial" works well.

However, the link to the Windows install for gfortran should be updated to the following link:

[http://www.equation.com/servlet/equation.cmd?fa=fortran](http://www.equation.com/servlet/equation.cmd?fa=fortran) 

There is a 32-bit and 64-bit versions of the latest as well as weekly versions of the GNU gcc builds, including OpenMP and other libraries.

It has been tested and works.

**Comment by certik** [comment]
@GS76 thanks for opening an issue for this. Would you mind submitting a pull request (PR) for this?

**Comment by GS76** [comment]
@certik, no problem. I will do so.

**Comment by LKedward** [comment]
Closing, fixed by #107. Thanks again @GS76

**Comment by GS76** [comment]
My pleasure. Thank you for everyone's assistance.
