### ISSUE TITLE
Binaries of gfortran for windows no longer available for download

### ISSUE THREAD

**Issue by smeskos** [fortran-lang/fortran-lang.org#134]
I am referring to the link that it is given in the quickstart tutorial [hello_world.md](https://github.com/fortran-lang/fortran-lang.org/blob/master/learn/quickstart/hello_world.md). 
Should we replace it with something else, eg. http://mingw-w64.org?

**Comment by milancurcic** [comment]
I think we should steer the Windows support toward WSL.

**Comment by GS76** [comment]
My apologies what does WSL refer to?

I am happy to use any type of installation of the Gfortran for Windows,
however, I just found the link we have now was easiest for Windows users, I
myself.

But I am happy to try others, as long as they are easy for the user.

Just my point of view.

**Comment by smeskos** [comment]
@GS76 WSL refers to Windows Subsystem for Linux, in short, you install a Linux distribution directly onto your Windows 10 (no virtual machine). This is an official Microsoft feature (not a 3rd party hack). Although it is not, yet, as robust as a clean Linux installation, and it lucks a GUI, you only get a bash, it is still a viable solution. 

@milancurcic I believe we need a new book about how to set up a Fortran environment in all major OS (including a list of the most common IDEs/Text-editors and how to configure them). From my experience with new Fortran users (from r/fortran and colleagues) they are usually Windows-only users with little programming experience. To push everyone toward WSL - a command-line-only Linux could bring a lot of frustration. 
For the moment we should just replace this link with something else that works. We could mention both MinGW and WSL and later add a link to a new book that will explain how to set them up.

**Comment by GS76** [comment]
@smeskos Thank you for the explanation. I will try it out. Your comments
below with regards Windows-only users with little programming experience is
100% accurate. I am in that category. I installed Linux about a 2 months
ago as I have always heard how much quicker it is than Windows. Anyway,
once up and running, I now understand what all the fuss is about and
compilers such as GCC and Gfortran are pre-installed, not necessarily the
correct version, but I can understand why programmers would like the
environment. I agree that we would need to show a complete installation
procedure, with WSL or whichever is most reliable and is guaranteed to be
the latest Gfortran.

**Comment by LKedward** [comment]
It is a shame these downloads stopped working - they offered a very easy install and packed in some useful extras like OpenMP and make.

> I believe we need a new book about how to set up a Fortran environment in all major OS (including a list of the most common IDEs/Text-editors and how to configure them).

Yes this idea has been discussed and is planned - if you are willing to make a start on this, that would be great!
Ideally this mini-book would present the main options available for Windows, their respective advantages/disadvantages, and instructions for each.

> I think we should steer the Windows support toward WSL.

The main disadvantage of WSL is that you need to use cross-compilation to compile native Windows binaries, which is a common reason for needing Windows support, but I agree it is _now_ a good solution for those comfortable with Linux command line.

> From my experience with new Fortran users (from r/fortran and colleagues) they are usually Windows-only users with little programming experience. To push everyone toward WSL - a command-line-only Linux could bring a lot of frustration.

Very true, but I don't know of many easy GUI setups for Fortran. I used [Geany](https://www.geany.org/) on Windows when I was learning because it supports Fortran, but you still need to install the compiler yourself I think.

**Comment by LKedward** [comment]
Looks like the download links are working again. We still have the problem of relying on this third-party site; a possible solution could be to setup a mirror.

**Comment by GS76** [comment]
I checked, Geany does not install Gfortran when installed.

**Comment by smeskos** [comment]
>Yes this idea has been discussed and is planned - if you are willing to make a start on this, that would be great!
>
I am, I will start today and will commit a PR as soon as I have a first draft.
