### ISSUE TITLE
Electronic structure Fortran projects

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fortran-lang.org#151]
Some other projects regarding electronic structure methods. Maybe a few of them are interesting as well, let me know and I will collect the necessary meta data.

name | url
--- | ---
 DFT-D4 | https://github.com/dftd4/dftd4
 ELPA | https://gitlab.mpcdf.mpg.de/elpa/elpa
 ELSI | https://gitlab.com/elsi_project/elsi_interface
 FortJSON | https://gitlab.com/elsi_project/fortjson
 libnegf | https://github.com/libnegf/libnegf
 NTPoly | https://github.com/william-dawson/NTPoly
 MBD | https://github.com/jhrmnn/libmbd
 mpifx | https://github.com/dftbplus/mpifx
 OpenMolcas | https://gitlab.com/Molcas/OpenMolcas
 scalapackfx | https://github.com/dftbplus/scalapackfx

**Comment by certik** [comment]
@awvwgk I would suggest to add any that have Fortran as the main programming language.
