### ISSUE TITLE
November 2020 Newsletter

### ISSUE THREAD

**Issue by ivan-pi** [fortran-lang/fortran-lang.org#162]
Has anyone started to work on this already?

The monthly call recording should be ready soon.

**Comment by milancurcic** [comment]
I haven't, though I planned it for this afternoon. Do you mind listing the PRs for one of the sections (website, stdlib, or fpm) and I can do the rest?

**Comment by milancurcic** [comment]
I'm putting together a website PR summary now.

**Comment by milancurcic** [comment]
Fixed by #163.
