### ISSUE TITLE
Newsletter on the October 2020 J3 meeting

### ISSUE THREAD

**Issue by milancurcic** [fortran-lang/fortran-lang.org#168]
There is a thread with a summary from the meeting [here](https://github.com/j3-fortran/fortran_proposals/issues/185).

Like we did with the [February meeting newsletter](https://fortran-lang.org/newsletter/2020/02/28/J3-february-meeting/), it would be useful to make and distribute a post about the progress made in the October meeting.

It looks like the GitHub issue thread could be largely adapted into a post. However, it would be helpful and nice to also have a brief discussion on the progress and future outlook, i.e. how did this meeting steer the course toward F202X.

The motivation for this is to leverage the fortran-lang reach and audience and promote the Committee's work.

What do you think? @certik @zjibben @sblionel @longb @rouson @gklimowicz @everythingfunctional @fortranfan @tclune @mleair

**Comment by certik** [comment]
I obviously agree, that is what I have been pushing all along and why Zach and I took our time to write things up.

However, I would appreciate more help from WG5 and J3 leadership. In my opinion it should be the leadership driving this effort, and I can of course help, but it shouldn't be me driving this, as I am not in the committee leadership.

**Comment by sblionel** [comment]
I'll be glad to do a writeup - probably for my blog as that's where I've written about standards progress before. Let me review the summary thread for ideas.

**Comment by milancurcic** [comment]
Thank you @sblionel. Would you agree to co-author your write-up with @certik and @zjibben who already wrote a useful summary, and cross-post the article on both fortran-lang.org and your website?

I understand if you prefer to write your own thing for your website. In that case, we (others) should still publish one on fortran-lang.org. I think what @certik and @zjibben wrote is a great start. I could help summarize the discussion that followed in that thread.

**Comment by FortranFan** [comment]
@milancurcic wrote Nov. 6, 2020, 10:35 AM EST: 

> There is a thread with a summary from the meeting [here](https://github.com/j3-fortran/fortran_proposals/issues/185).
> 
> Like we did with the [February meeting newsletter](https://fortran-lang.org/newsletter/2020/02/28/J3-february-meeting/), it would be useful to make and distribute a post about the progress made in the October meeting.
> 
> It looks like the GitHub issue thread could be largely adapted into a post. However, it would be helpful and nice to also have a brief discussion on the progress and future outlook, i.e. how did this meeting steer the course toward F202X.
> 
> The motivation for this is to leverage the fortran-lang reach and audience and promote the Committee's work.
> 
> What do you think? @certik @zjibben @sblionel @longb @rouson @gklimowicz @everythingfunctional @FortranFan @tclune @mleair


As you all will know, J3 also puts the meeting minutes which may be useful to reference in the newsletter: https://j3-fortran.org/doc/year/20/minutes222.txt

Great job on the newsletter.

**Comment by sblionel** [comment]
@milancurcic , I think the idea of separate posts would work better. I can write mine from the WG5 perspective, and others can write one from the user perspective. We should cross-link the posts.

**Comment by awvwgk** [comment]
This seems to be resolved.
