### ISSUE TITLE
Find a package does not work on Firefox with ETP

### ISSUE THREAD

**Issue by jme52** [fortran-lang/fortran-lang.org#175]
The "Find a package" search functionality of https://fortran-lang.org/packages/ does not work for me on Firefox (78.4.0esr, 64-bit, linux) when Enhanced Tracking Protection is On.  By "does not work" I mean that, when ETP is enabled:
- There is no visible list of tags under "Featured topics".
- The search results page (e.g., https://fortran-lang.org/packages/search/?query=lapack) is always an empty list.

**Comment by awvwgk** [comment]
Search functionality works fine with Mozilla Firefox 83.0 on 64 bit Manjaro Linux with _Enhanced Tracking Protection_ for me.

**Comment by jme52** [comment]
Thank you for checking.  I tried again with a new profile, and it works with ETP.

It's strange: when using ETP, in the new profile Firefox tells me that "No trackers known to Firefox were detected on this page", but in my normal profile (no extensions, clean cache) I get two blocked tracked contents: https://fonts.googleapis.com and https://ajax.googleapis.com .

**Comment by awvwgk** [comment]
This might be resolved with the migration to the new webpage see #415
