### ISSUE TITLE
Multi-word tags in packages

### ISSUE THREAD

**Issue by jme52** [fortran-lang/fortran-lang.org#176]
Is it possible to have tags that use multiple words separated by spaces?

At the moment there are packages that define multi-word tags with hyphens ("electronic-structure-calculations"), and packages where the same words are separated by spaces, thus actually creating multiple tags (electronic structure calculations).  This results in duplicated tags in the list of featured topis on https://fortran-lang.org/packages/ (e.g., I can see "electronic-structure", "electronic" and "structure"), which prevents other tags from appearing there at all.

**Comment by LKedward** [comment]
Agreed, the tag implementation is a little messy currently and could do with a cleanup so that the tag cloud is more representative of the packages.

**Comment by LKedward** [comment]
An alternative solution could be to simply use a manually curated list of tags on the package page.

**Comment by jme52** [comment]
I created a PR that I think partially addresses the issue - at least insofar as electronic structure and other related popular multi-word tags are involved.  I was not able to visualize the tag cloud in my build, so I would be grateful if somebody with the right repository permissions could trigger the appropriate GitHub action so that we can check the preview.

**Comment by ivan-pi** [comment]
Closed by #216
