### ISSUE TITLE
Intel compiler info needs to be updated on website

### ISSUE THREAD

**Issue by ElAlderson** [fortran-lang/fortran-lang.org#185]
Intel Parallel Studio XE has been rebranded to [Intel oneAPI](https://software.intel.com/content/www/us/en/develop/tools/oneapi/commercial-base-hpc.html) which now contains two FORTRAN compilers: Intel FORTRAN Compiler Classic (`ifort`) and Intel FORTRAN Compiler Beta (`ifx`). [Choosing a compiler](https://fortran-lang.org/learn/os_setup/choose_compiler) and [Fortran Compilers](https://fortran-lang.org/compilers/) pages need to be updated accordingly.

**Comment by LKedward** [comment]
Duplicate of #181

**Comment by LKedward** [comment]
Bonsoir @ElAlderson, thanks for reporting 👍

**Comment by ElAlderson** [comment]
> 
> 
> Bonsoir @ElAlderson, thanks for reporting 👍

No problem!
