### ISSUE TITLE
Localization of the webpage

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fortran-lang.org#197]
Is there a way we can offer localization with the current website design? What would we have to do from a technical point of view to be able to put up a localized version of fortran-lang.org?

Inspired by @vmagnin's post at https://fortran-lang.discourse.group/t/promoting-fortran-in-non-english-languages/678

**Comment by certik** [comment]
Yes I think that is a good idea, as long as people are willing to maintain the translations. Here is how we do it in for the SymPy's webpage:

https://github.com/sympy/sympy.github.com#translations

**Comment by vmagnin** [comment]
As written in the Discourse, if translating pages is decided, I of course agree to work on the french translation. And of course, it could be a collaborative work if there is other people interested here.

**Comment by awvwgk** [comment]
@vmagnin Definitely, I consider it more a matter of figuring out the technicalities to get this running with jekyll. I already found plenty of ugly solutions when searching for `jekyll i18n`, but nothing that strikes me as elegant and simple yet.

On this topic, I would contribute to German translations.

**Comment by vmagnin** [comment]
> Definitely, I consider it more a matter of figuring out the technicalities to get this running with jekyll.

Yes, the main problem is probably a technical one. How to transform the site into a multi-language site... It seems not trivial... And would probably need a lot of work.

**Comment by vmagnin** [comment]
Maybe we could, at least as a first step, just translate the homepage. Perhaps it would be sufficient to make the site appears in Google with a good pagerank. I don't know if the number of pages available in the national language is taken into account in the Google algorithm... We could even make an experiment: we translate the homepage just in one language, and we wait some days (or weeks ?) to see if it has an effect on search engines.

**Comment by awvwgk** [comment]
I found [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin) which allows side localization with jekyll in an elegant way. First, I already created a branch [i18n](https://github.com/awvwgk/fortran-lang.org/tree/i18n), where you can give it a try.

1. add your language in the `_config.yml` under `languages` (the first language is the default)

https://github.com/fortran-lang/fortran-lang.org/blob/f14c12f183ecdf6cfdb910729ce928f79d329f85/_config.yml#L7

2. create the file `_i18n/<lang>.yml` and the directory `_i18n/<lang>` (now you can visit `http://127.0.0.1:4000/<lang>/` already, untranslated pages are taken from the default language branch)
3. mirror the content of `_i18n/en` in your `_i18n/<lang>` directory, *i.e.* create `_i18n/<lang>/index.html` to translate the main page
 
There are a lot of small details I still have to figure out, but this basically looks like a suitable solution for the webpage.

**Comment by vmagnin** [comment]
>     3. mirror the content of `_i18n/en` in your `_i18n/<lang>` directory, _i.e._ create `_i18n/<lang>/index.html` to translate the main page

@awvwgk , I have forked your repository. I will try these days to translate just the homepage to begin. Just a question concerning your third point: should I mirror _all the content_ of `_i18n/en` ? or just the files I want to translate ? (it's what I understand, but I am not sure...)

Another newbie question: I guess that to access to `http://127.0.0.1:4000/<lang>/` I need to install jekyll on my machine?

**Comment by awvwgk** [comment]
@vmagnin Just adding the files you translate is sufficient, the rest will be filled in automatically from the `_i18n/en` tree. Let me know if this works as expected. Note, currently my setup only allows to translate the body but not the keywords in the header and footer and so on, but I will look into this soon.

To setup the webpage locally follow the guide in the README at https://github.com/fortran-lang/fortran-lang.org#setup. After you have setup everything run `bundle exec jekyll serve --watch` in another terminal and open `http://127.0.0.1:4000` in your webbrowser to get a live preview while you edit the content.

**Comment by aslozada** [comment]
This procedure works correctly. Jekyll server returns some warnings about deprecated arguments.

```fortran-lang.org/.bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/tags/include.rb:194: warning: Using the last argument as keyword parameters is deprecated```

I am trying with a Spanish translation

**Comment by vmagnin** [comment]
I have done everything, including _i18n/fr.yml and _i18n/fr/index.html
I can access to my local english version, but not the french version with http://127.0.0.1:4000/fr/ in my web browser:
**Not Found
`/fr/' not found.
WEBrick/1.6.0 (Ruby/2.7.1/2020-03-31) at 127.0.0.1:4000**
 
Should I install  jekyll-multiple-languages-plugin  with bundle ? I don't see it when I type "bundle install" (but I see `Installing i18n 0.9.5`)

**Comment by vmagnin** [comment]
Sorry, my second terminal (the jekyll one) was not opened in the i18n but the master branch...
Now bundle install successfully installed the  jekyll-multiple-languages-plugin
It's OK, I have translated one sentence and I see it in http://127.0.0.1:4000/fr/
:-)

**Comment by awvwgk** [comment]
I put together a first draft patch for the localized homepage at #201, if you want to give it a try, there is now support for localizing (most of the) keywords in the navigation and footer and adding translated pages. The process is outlined [here](https://github.com/awvwgk/fortran-lang.org/blob/i18n/TRANSLATING.md).

It has still a few rough edges, so feedback is much appreciated. Stay tuned.

**Comment by aslozada** [comment]
Would it appropriate build a branch to each language during translation process?

e.g.

```
i81n
|
| -- Default language
| -- English
| -- Spanish
| -- French
| -- German
| -- Czech
...
```

**Comment by aslozada** [comment]
> I put together a first draft patch for the localized homepage at #201, if you want to give it a try, there is now support for localizing (most of the) keywords in the navigation and footer and adding translated pages. The process is outlined [here](https://github.com/awvwgk/fortran-lang.org/blob/i18n/TRANSLATING.md).
> 
> It has still ~a few~ plenty rough edges, so feedback is much appreciated. Stay tuned.

@awvwgk. If the general layout (_i18n /_layouts) is kept fixed, the final aspect of the footer is modified by adding words with a greater number of characters.  Some "line breaks" are introduced.

**Comment by vmagnin** [comment]
> Would it appropriate build a branch to each language during translation process?

In my opinion, it is not necessary, each language having its own directory. And it would multiply the number of branches in the project.

**Comment by aslozada** [comment]
> > I put together a first draft patch for the localized homepage at #201, if you want to give it a try, there is now support for localizing (most of the) keywords in the navigation and footer and adding translated pages. The process is outlined [here](https://github.com/awvwgk/fortran-lang.org/blob/i18n/TRANSLATING.md).
> > It has still ~a few~ plenty rough edges, so feedback is much appreciated. Stay tuned.
> 
> @awvwgk. If the general layout (_i18n /_layouts) is kept fixed, the final aspect of the footer is modified by adding words with a greater number of characters. Some "line breaks" are introduced.

Thanks, @vmagnin. Yes, my comment is a bit confusing. 
Perhaps the following images describe better,

Footer in the English version
![english](https://user-images.githubusercontent.com/3170541/107626264-4a944280-6c3c-11eb-9bf3-1e05aeda1c42.png)

Footer in the Spanish version
![spanish](https://user-images.githubusercontent.com/3170541/107626363-6ef01f00-6c3c-11eb-8650-5cec206c8c16.png)

**Comment by awvwgk** [comment]
I see, yes they are currently just 33% of the column wide. If we will have many languages there might be even problematic with the language keys as well. I will probably try two rows in the footer instead.

**Comment by vmagnin** [comment]
@aslozada , no, not confusing. My emoji was just meaning I have the same annoying (minor) problem. In my case, even for the GitHub message on the right.

**Comment by awvwgk** [comment]
I made a second line for the languages, if we get many translations and small screens (mobile) line breaks can't be avoided, but this is something to worry about once we have that much translations:

![image](https://user-images.githubusercontent.com/28669218/107696765-a699ae00-6cb2-11eb-9324-83ceba9aba3c.png)

**Comment by awvwgk** [comment]
This issue will be resolved with the migration to the new webpage at https://github.com/fortran-lang/webpage (see #415).
