### ISSUE TITLE
Flang link on the compiler page

### ISSUE THREAD

**Issue by arunningcroc** [fortran-lang/fortran-lang.org#198]
The "LLVM Flang" link on the compilers page seems to be broken.

https://fortran-lang.org/compilers/

The link leads to: https://github.com/llvm/llvm-project/tree/master/flang which is now a 404.

It seems that the LLVM flang project has now been merged to https://github.com/flang-compiler/flang which is listed on the compilers page as "Current Flang".

**Comment by awvwgk** [comment]
LLVM renamed their default branch from master to main, the link should now point to https://github.com/llvm/llvm-project/tree/main/flang

**Comment by awvwgk** [comment]
> It seems that the LLVM flang project has now been merged to https://github.com/flang-compiler/flang which is listed on the compilers page as "Current Flang".

Note that LLVM *flang* (former *f18*) is the successor of what is known as current *flang*, which in turn is based on the *pgfortran* frontend (now known as *nvfortran*). As announced inoffically on the NVIDIA forum *nvfortran* will at some point be using the LLVM *flang* frontend (see https://forums.developer.nvidia.com/t/fortran-2008-2018-support/164306).

**Comment by milancurcic** [comment]
The PGI/NVIDIA/Flang compiler evolution/branding has been the most confusing of any compiler I've seen.
