### ISSUE TITLE
Link teaching resources and course material?

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fortran-lang.org#200]
Is it on scope for the webpage to link external course material or teaching resources from the *learn* page? I'm mainly thinking about pure Fortran programming courses and also more domain-specific specific courses that include Fortran introductions to teach other more specific concepts.

If we agree that it is on scope, what would be criteria to list a course on the *learn* page?

**Comment by ivan-pi** [comment]
I'm aware of several great resources including:

* [Programming in Fortran](https://doku.lrz.de/display/PUBLIC/Programming+with+Fortran) (course offered at the Leibniz-Rechenzentrum)
* [PRACE Course: Advanced Fortran Topics](https://doku.lrz.de/display/PUBLIC/PRACE+Course%3A+Advanced+Fortran+Topics)
* [Kursmaterial für Wissenschaftliches Programmieren (Modern Fortran, 2017)](https://www.bccms.uni-bremen.de/cms/people/b-aradi/wissen-progr/modern-fortran/2017) from Bálint @aradi at Bremen Center for Computational Materials Science
* [Modern Fortran Programming for Chemists and Physicists](http://www.chem.helsinki.fi/~manninen/fortran2014/), course by Pekka Manninen from University of Helsinki
* [Expressing Object-Oriented Concepts in Fortran90 ](http://www.cs.rpi.edu/~szymansk/OOF90/Forum.html)
* [Parallel Programming Workshop](https://fs.hlrs.de/projects/par/par_prog_ws/) (materials from the High-Performance Computing Center in Stuttgart)
* [Programming in Modern Fortran](https://cyber.dabamos.de/programming/modernfortran/) (I believe this is a tutorial written by @interkosmos)
* [2018 Workshop on Fortran Modernization for Scientific Applications](https://tcevents.chem.uzh.ch/event/3/) (with lectures by @arjenmarkus and @aradi)
* [Introduction to Programming using Fortran 95/2003/2008](http://www.egr.unlv.edu/~ed/fortranv3.pdf)
* [Scientific Programing and Numerical Computation](http://homepage.ntu.edu.tw/~wttsai/fortran/) (course by Wu-ting Tsai from National Taiwan University; the explanation of FFT is great!)
* [Introduction to Modern Fortran](https://www-uxsup.csx.cam.ac.uk/courses/moved.Fortran/) (course given by Nick Maclaren from the University of Cambridge Computing Service, derived from a course by Steve Morgan from the University of Liverpool; I think this course offers some good arguments why Fortran is more suitable for domain scientists than C++)

Personally, I find these resources very helpful. I've got several more links hidden in my browser bookmarks :exploding_head: . 

As a temporary solution, I would feel okay to put these in the "Other Resources" section on the Learn page. But it might be a good idea to introduce some further subcategories (e.g. links related to the standards committee, Fortran blogs, third-party lectures, ...).

I also think we should ask the authors for permission to link their lectures. Some of them might be available openly only for convenience of access for the students taking their courses, and not really meant for the general public.

**Comment by milancurcic** [comment]
I agree it's in scope. About criteria, I don't know, good question. I agree with @ivan-pi on recent material. Otherwise I think it will be difficult to come up with hard criteria, especially for say, quality. I'd say let's list everything we can find that we collectively and subjectively agree is high enough quality to be useful. I think most finished tutorials out there will meet this "criterion".

I think we should also link paid courses like that of @everythingfunctional. But we need to clearly mark is as non-free. 

I suggest not including courses that happened in the past and don't provide course notes for download (e.g. I couldn't find any from the 2018 Workshop on Fortran Modernization for Scientific Applications).

**Comment by ivan-pi** [comment]
> I suggest not including courses that happened in the past and don't provide course notes for download (e.g. I couldn't find any from the 2018 Workshop on Fortran Modernization for Scientific Applications).

They are linked in the [timetable](https://tcevents.chem.uzh.ch/event/3/timetable/#20180606) (similar to FortranCon2020).

**Comment by certik** [comment]
I think this is definitely in scope. Thanks @ivan-pi for the list. I think we can be inclusive an link pretty much anything, as long as we neatly organize it so that people reading the page can find what they want.

**Comment by milancurcic** [comment]
> They are linked in the timetable (similar to FortranCon2020). Perhaps ease of access is another criterion.

Alternatively we can obtain permission from authors and organizers and host the material on our website.

**Comment by aradi** [comment]
As for me, you are very welcome to link my Scientific programming course (I'll probably record a new version with youtube videos this spring). You have also definitely my permission to link or host the material I used on the 2018 workshop.

**Comment by ivan-pi** [comment]
Thanks @aradi.

In the meantime I updated the list with a few more courses. Perhaps some categorization would be beneficial, like courses which cover co-arrays, object-oriented features, F77 to F90 conversion

**Comment by vmagnin** [comment]
I propose that we include a few non-english courses, like the german one proposed by @ivan-pi .
Concerning the French language, I therefore propose that link:
[http://www.idris.fr/formations/fortran/](http://www.idris.fr/formations/fortran/)
Those very complete courses include Fortran 2003 and 2008 stuff. Not yet Fortran 2018, although there is some slides on obsolete features in the 2018 standard. But they seem to be regularly updated (two from 2020, one from 2019). Note that IDRIS is a department of the CNRS, the big french national research center.

**Comment by vmagnin** [comment]
Following that discussion https://fortran-lang.discourse.group/t/ref-card-for-fortran90/935/ , I propose to add on the Learn page a Fortran refcard, like that one:
https://michaelgoerz.net/refcards/fortran_refcard_a4.pdf
I could contact the author on https://github.com/goerz/Refcards to ask if it is the latest PDF version, the LaTeX source available on GitHub having a last commit in Dec. 2018 (CC-BY-NC-SA license).
