### ISSUE TITLE
books to add

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fortran-lang.org#202]
[Fortran 2018 with Parallel Programming](https://www.routledge.com/Fortran-2018-with-Parallel-Programming/Ray/p/book/9780367218430) (2019) by Subrata Ray
[Introduction to Computational Economics Using Fortran](https://www.ce-fortran.com/) (2018) by Hans Fehr and Fabian Kindermann

**Comment by awvwgk** [comment]
Books can be added at https://github.com/fortran-lang/fortran-lang.org/blob/master/_data/learning.yml, I opened #206 to add the two books.
