### ISSUE TITLE
Small error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by vmagnin** [fortran-lang/fortran-lang.org#209]
In the workflow section, I read:
> 4. Push your modified branch to your **local** fork
    e.g. git push --set-upstream origin fix-spelling-homepage

I guess it should be "to your distant fork" (or remote fork?)

**Comment by awvwgk** [comment]
Not sure what the best formulation here would be, but *local* is not optimal, maybe one could drop the *local* without problems here. Feel free to send a patch with an improved formulation on this part.
