### ISSUE TITLE
Add package guide to webpage

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fortran-lang.org#210]
The package guide is currently just a [markdown file in this repository](https://github.com/fortran-lang/fortran-lang.org/blob/master/PACKAGES.md), but would be very well suited for the webpage as well. Since the markdown file contains some technicalities specific to the jekyll setup as well, those could be separated and added to the wiki in the repository.

Related fortran-lang/webpage#70

**Comment by zmoon** [comment]
@awvwgk how would you suggest doing this while keeping a single source? GH Action to update the wiki page based on the Jekyll version (skipping the YAML FM) could work?

**Comment by awvwgk** [comment]
I was thinking about splitting the guidelines from the technical workflow, no need for a single source in this setup.

**Comment by zmoon** [comment]
Ah ok gotcha. Would that be everything under "Package index requests"?

**Comment by awvwgk** [comment]
This is resolved with the new webpage (see #415)
