### ISSUE TITLE
Other commercial compilers with free community versions

### ISSUE THREAD

**Issue by zmoon** [fortran-lang/fortran-lang.org#214]
Maybe the compilers page could mention that the NVIDIA offering [is currently available for free](https://news.developer.nvidia.com/hpc-sdk-ga-2020/), like it does for Intel.

**Comment by milancurcic** [comment]
I agree--mind filing a PR?

Should we say the same thing about the AMD compiler? It looks like it's free to download but I haven't tried it.

**Comment by awvwgk** [comment]
Most of the commercial compilers are offering free community versions.

I think we should include this information for the commercial compilers, maybe together with known platform and architecture constraints:
- Intel oneAPI, x86_64, Linux / Windows / MacOS
- NVHPC, x86_64 / PowerPC / ARM, Linux
- IBM XL, PowerPC, Linux / AIX
- AOCC, x86_64, Linux
