### ISSUE TITLE
Build preview committer

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/fortran-lang.org#224]
I wonder how the <code>#</space>build_preview</code> action is picking up the commit author for the preview build? It seems to just take the identity from the latest committer to the default branch for creating the commit instead of the actor triggering the  <code>#</space>build_preview</code> in the pull request or the pull request author.

**Comment by LKedward** [comment]
It looks like this is the default behaviour for the [EndBug/add-and-commit](https://github.com/EndBug/add-and-commit) action that we're currently using. We could probably follow [these instructions](https://github.com/EndBug/add-and-commit#examples) to change the committer to the github actions bot or just not use this action for pushing the preview.
