### ISSUE TITLE
Duplicates of M_CLI and M_CLI2 in the fpm registry page

### ISSUE THREAD

**Issue by vmagnin** [fortran-lang/fortran-lang.org#239]
In the fpm registry page (https://fortran-lang.org/packages/fpm), I have found that there is duplicates of :

- M_CLI
- M_CLI2

It seems to be due to the fact that in the links there is one `M_CLI` and one `M_cli` (lowercase). Same for `M_CLI2` and  `M_cli2`.

Suggestion: with an alphabetical sort those problems could be more visible.

**Comment by awvwgk** [comment]
Duplicate of https://github.com/fortran-lang/fpm-registry/issues/31

**Comment by awvwgk** [comment]
Resolved with https://github.com/fortran-lang/fpm-registry/pull/38
