### ISSUE TITLE
Typo in fortyxima

### ISSUE THREAD

**Issue by ivan-pi** [fortran-lang/fortran-lang.org#248]
https://github.com/fortran-lang/fortran-lang.org/blob/cd7baa0b3e98907251a98e556871409a451970c2/_data/package_index.yml#L153

Should read "fortyxima"

**Comment by awvwgk** [comment]
Thanks, do you mind submitting a patch?

**Comment by henilp105** [comment]
I have made the necessary changes please check and  merge pull request.

thanks and Regards,
Henil Panchal
