### ISSUE TITLE
Add gemini3d

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#250]
We should add

https://github.com/gemini3d/gemini3d

into our packages list.

**Comment by awvwgk** [comment]
Sounds good to me, do you want to go ahead and send a patch?

**Comment by certik** [comment]
@scivision would you have time to send a patch? I am busy right now.

**Comment by awvwgk** [comment]
Done with https://github.com/fortran-lang/fortran-lang.org/pull/259
