### ISSUE TITLE
Content using `book` layout sometimes not visible

### ISSUE THREAD

**Issue by zmoon** [fortran-lang/fortran-lang.org#256]
Between the mobile breakpoint and ~ 900 px, the content is not all visible on the screen without scrolling horizontally. 

900: https://screenfly.org/#u=https%3A//fortran-lang.org/learn/quickstart/arrays_strings&w=900&h=900
600: https://screenfly.org/#u=https%3A//fortran-lang.org/learn/quickstart/arrays_strings&w=600&h=900

**Comment by certik** [comment]
We should move the left navigation panel to the top, then the horizontal area can be used more effectively.

**Comment by awvwgk** [comment]
This should be resolved with the migration to the new webpage.
