### ISSUE TITLE
Fortran Best Practices -- typos and grammar

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fortran-lang.org#316]
I'll create a PR eventually. Since the PR in my previous fork has been incorporated, can I delete that fork and fork the current repo?

"purpose" not "purse" in "every procedure starts with a comment briefly describing its purse and the intent of the dummy arguments" at https://fortran-lang.org/learn/best_practices/modules_programs

"on" not "one" in "Similarly, exports are made explicitly by adding a private statement one a single line and explicitly listing all exported symbols in public statements." (same page)

For "Variables inside a module are static (implicitly saved), it is highly recommended to limit the usage of module variables to constant expressions, like parameters or enumerators only or export them as protected rather than public." start a second sentence at "it".

Change "Reusing implementations from modules allows to write reusable code and focus in the program unit only on translating user input to the respective library functions and objects." to "Reusing implementations from modules allows **you** to write reusable code and focus the program unit on conveying user input to the respective library functions and objects."

In "In the following example the inverse distance between two sets of points is evaluated, note that the points are stored contiguously in the arrays xyz1/xyz2, while the inner-most loop is advancing the left-most index of the matrix a." start a new sentence at "note" . Page is https://fortran-lang.org/learn/best_practices/multidim_arrays.

"then" not "than" in "The function can than be used with a callback by importing the module as shown in the following example" at https://fortran-lang.org/learn/best_practices/callbacks

**Comment by awvwgk** [comment]
> I'll create a PR eventually. Since the PR in my previous fork has been incorporated, can I delete that fork and fork the current repo?

If you go to your fork there is a Fetch upstream button to sync your repo again:

![image](https://user-images.githubusercontent.com/28669218/132171828-ed7d165c-8e37-48b2-aa9d-96bd856af896.png)
