### ISSUE TITLE
Add search capability to site

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fortran-lang.org#322]
It would be nice if fortran-lang.org had a search bar. Python.org and isocpp.org do.

**Comment by awvwgk** [comment]
We might be able to do this easily when switching our static side generator to sphinx + MyST (see #89), which would also allow having translations of the webpage. But I haven't got around to follow up on this issue yet, too much other stuff to do.

**Comment by certik** [comment]
Yes. And when I was talking about tutorials, I meant these: https://github.com/fortran-lang/fortran-lang.org/tree/master/learn/quickstart which are already in Markdown, so converting to MyST will be super easy.

The last big things to convert from fortran90.org is: https://www.fortran90.org/src/rosetta.html, and we can do it by hand, it's not that big of a deal.

**Comment by awvwgk** [comment]
This functionality will be available once we migrate to https://github.com/fortran-lang/webpage (see #415), sphinx offers a side wide search by default.
