### ISSUE TITLE
Formatting of Derived Types page

### ISSUE THREAD

**Issue by Beliavsky** [fortran-lang/fortran-lang.org#332]
At https://fortran-lang.org/learn/quickstart/derived_types , using Chrome on Windows, if I magnify the page enough with Cntrl+ , and I use the scroll bar on the right, the words at the bottom, Learn, Compilers, Community, Packages, News are sometimes on top of the the text under Quickstart Fortran Tutorial.

**Comment by awvwgk** [comment]
This should be fixed with the migration to the new webpage (see #415)
