### ISSUE TITLE
Consider renaming default branch to `main`

### ISSUE THREAD

**Issue by tclune** [fortran-lang/fortran-lang.org#338]
Just a socially conscious recommendation.

https://github.com/github/renaming

**Comment by certik** [comment]
Thanks. We considered that and renamed other repositories. But with this one we need to do quite a few fixes:

https://github.com/fortran-lang/fortran-lang.org/search?q=master

However if you send us PRs, it can happen faster. :)

**Comment by awvwgk** [comment]
Duplicate of https://github.com/fortran-lang/fortran-lang.org/issues/325

**Comment by awvwgk** [comment]
This repository will be migrated to https://github.com/fortran-lang/webpage soon (see #415), where we use *main* as name for the default branch.
