### ISSUE TITLE
FOSDEM 2022

### ISSUE THREAD

**Issue by jvdp1** [fortran-lang/fortran-lang.org#354]
[FOSDEM 2022](https://fosdem.org/2022/news/2021-11-30-accepted-developer-rooms/) will be virtual again.
Any interest to present some fortran-lang projects there? The deadline for submitting abstracts is quite close (end Dec.).

**Comment by awvwgk** [comment]
Maybe post on discourse for a broader audience. I think stdlib has been moving quite a bit since FortranCon, also I'm done for a while with presenting fpm at conferences ;).

**Comment by jvdp1** [comment]
> Maybe post on discourse for a broader audience. I think stdlib has been moving quite a bit since FortranCon, also I'm done for a while with presenting fpm at conferences ;).

Undersood ;)
I will mention it on Discourse, at least to announce it.  Unfortunately I don't have time right now for `stdlib`.

**Comment by awvwgk** [comment]
This has resolved itself, I guess.
