### ISSUE TITLE
Verifying VS Code Publisher

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fortran-lang.org#404]
Our VS Code Publisher is register as the Fortran Lang organisation and points to the official webpage https://fortran-lang.org. Microsoft allows for Organisations to verify their publisher IDs by proving they own the domain they list see: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#verify-a-publisher

I think it would make use look substantially more official if we verified the publisher ID.
These are the steps that need to be made in order to verify (copy-pasted from the manager portal of the publisher ID. @awvwgk can also view them if he logs in [here](https://marketplace.visualstudio.com/manage/publishers/fortran-lang?noPrompt=true) and goes to Verified domain)

1. Create a TXT record in your DNS configuration for the following hostname:_visual-studio-marketplace-fortran-lang.fortran-lang.org
2. Use this code as the value for the TXT _**! redacted !**_
3. Wait until your DNS configuration changes. This could take up to 72 hours. 

I have redacted the value of the txt file in 2. in case this information is not set through a PR on GitHub but through some private backend. If that is the case, I can send the value privately or Sebastian can get it directly.

**Comment by milancurcic** [comment]
Thanks @gnikit, the TXT record is now live.

**Comment by gnikit** [comment]
Awesome, thanks a lot @awvwgk @milancurcic !
