### ISSUE TITLE
Create a Preview for each PR

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#41]
Right now we have to test a PR locally that it works. Our CI should create a preview of each PR, so that we can simply see it right away. Typically that is achieved by pushing the PR into some review github pages as a branch with a url prefix so each PR has its own prefix and we can check that the page looks good.

**Comment by certik** [comment]
We had to revert the fix, so I am reopening the issue also.

**Comment by LKedward** [comment]
I think this needs re-opening unfortunately,
Test PR #55 [failed to push](https://github.com/fortran-lang/fortran-lang.org/runs/653365902?check_suite_focus=true) the preview build to the repo.

There's a permissions problem.

**Comment by milancurcic** [comment]
I don't see any failure in that link. What kind of permission is needed?

**Comment by LKedward** [comment]
> I don't see any failure in that link.

Yeah it's a bit annoying, the marketplace action for pushing to the repo completes successfully even if the push failed.
Look under ` > Commit and push to gh-pages` / ` > Internal logs`.

It seems the github action for pull requests from forks [only has read-only access](https://github.community/t5/GitHub-Actions/Token-permissions-for-forks-once-again/td-p/33839#).

I think a solution can be to have the preview build triggered explicitly when someone with write access comments `#build_pr` or something. I will look into this.

**Comment by milancurcic** [comment]
If we add you as collaborator with permissions on this repo, would you know how to set it up?

**Comment by LKedward** [comment]
> If we add you as collaborator with permissions on this repo, would you know how to set it up?

Yes I believe so
