### ISSUE TITLE
[BUG] Unable to change between New Topic and New Message options on Discourse

### ISSUE THREAD

**Issue by gnikit** [fortran-lang/fortran-lang.org#413]
I noticed a change in Fortran-lang Discourse and I am relatively sure that it is a bug. When creating a new topic you used to be able to choose by clicking the `+` sign between:
- New Topic
- New Message

![image](https://user-images.githubusercontent.com/16143716/176868711-8f6f6921-ac4b-4547-8d77-2775df7e5853.png)

Now the only available option is the *New Topic*.

The easiest way to send a message now is: `Go to your profile > Messages > New Message` and even then the only available option when pressing the `+` sign is *New Topic*

![image](https://user-images.githubusercontent.com/16143716/176869133-e9ba4685-e9d6-40d6-97d6-562103243d79.png)

**Comment by milancurcic** [comment]
How do you know it's a bug and not an intentional UI change? I agree it's not as easy to send messages as it is to open new topics.

Another "easy" way to send a message is to click on a user and press the "Message" button.

**Comment by gnikit** [comment]
> How do you know it's a bug and not an intentional UI change?

I would suspect that if it was a feature in the second case you would be able to swap between *New Message* and *New Topic*, but if you click *New Topic*, you are unable to get back to *New Message*, so you have to discard the message and start again.

**Comment by milancurcic** [comment]
I agree that's weird UI, though I never tried doing that (I didn't even know you can click on the + or the envelope to change the mode until just now).

**Comment by gnikit** [comment]
Another thing I noticed on Discourse that might be related to things "breaking" or it might be a completely other thing that needs its own issue, is that replying to someone's answer does not always show once you post your reply. I do not recall that always being the case and I have examples as new as 6d ago where it worked. Maybe it is has something to do with the category of the posts? I really don't know.

What I typed:
![image](https://user-images.githubusercontent.com/16143716/176932751-17e99152-7eb0-4851-8eb8-58ac06bd9b4f.png)
vs How it displays:
![image](https://user-images.githubusercontent.com/16143716/176932822-0f30ab34-ef35-4c7b-aff5-026ee5ad46ec.png)

thread is here: https://fortran-lang.discourse.group/t/fortran-developers-poll-2022/3877/6

What is should look like:
![image](https://user-images.githubusercontent.com/16143716/176933164-c101a1eb-32f5-428b-a1e5-2695f30222ae.png)
thread is here: https://fortran-lang.discourse.group/t/asking-questions-in-fortran-lang-already-posted-in-stack-overflow/3828/5

**Comment by gnikit** [comment]
Thanks, I suspected it might related to upstream.

**Comment by milancurcic** [comment]
It's still useful to raise these questions within Fortran-lang, as there have been many tweaks to the Fortran Discourse that we could change on our end, so I didn't mean to discourage you from opening them here. Opening a Meta post on Fortran-lang Discourse is more appropriate for those than a GitHub issue here.

**Comment by gnikit** [comment]
Sure thing, and I of course I am not discouraged by your reply, but I closed the report promptly to keep the number of open issues to a manageable level. Will post on Fortran-lang>Meta next time, cheers.
