### ISSUE TITLE
Makefile under `An introduction to make` not rebuilding when included files are changed

### ISSUE THREAD

**Issue by p-costa** [fortran-lang/fortran-lang.org#416]
I hope this is worth opening an issue here.

In addition to *fpm*, I actually use the nice `Makefile` and dependencies generator under [An introduction to make](https://fortran-lang.org/learn/building_programs/project_make) in some projects. The `Makefile` has a dependencies generator which parses Fortran sources to search for dependencies, also for `include`d files, but does not re-build when these include files are changed.

See this example project:
```
$> tree
.
├── gen-deps.awk
├── Makefile
└── src
    ├── bla.f90
    ├── bla-inc.f90


$> cat src/bla.f90
module bla
  implicit none
  private

  public :: say_hello
contains
  subroutine say_hello
    include "bla-inc.f90"
    print *, "Hello, bla!"
  end subroutine say_hello
end module bla


$> cat src/bla-inc.f90
print*,'Hey!'

$> cat Makefile
(...)
# List of all source files
SRCS := src/bla.f90
TEST_SRCS :=
(...)
```
When I `touch src/bla.f90`, the project is correctly rebuilt, but not when I `touch src/bla-inc.f90`. Unfortunately, I'm not proficient enough with GNU make to fix this, but maybe someone can!

**Comment by awvwgk** [comment]
Looks like I'm resolving the included file too often, this seems like the appropriate fix to me:

```diff
diff --git a/learn/building_programs/project_make.md b/learn/building_programs/project_make.md
index fc2ede28..c3045bd6 100644
--- a/learn/building_programs/project_make.md
+++ b/learn/building_programs/project_make.md
@@ -262,7 +262,7 @@ $2 ~ /^["'].+["']$/ {
     # count included files per file to avoid having duplicates in our list
     if (incc[FILENAME,$2]++ == 0) {
         # Add the included file to our list, this might be case-sensitive
-        inc[++ii] = sprintf("$(%s) += $(%s)", FILENAME, $2)
+        inc[++ii] = sprintf("$(%s) += %s", FILENAME, $2)
     }
 }
 
```

Not all Fortran compilers will search in the same directory for include files, assuming relative includes from the current file is therefore not portable. If you want to have make search your source tree for include files [`vpath`](https://www.gnu.org/software/make/manual/html_node/Selective-Search.html#Selective-Search) is the way to go

```make
vpath % .:src
```

Best translate the include flags used in your project using `patsubst` to the `vpath` to be sure you have included all possible locations. Something like this might work (untested)

```make
vpath % $(subst $(eval) ,:,$(patsubst -I%,%,$(filter -I%,$(INCLUDE_FLAGS))))
```

**Comment by p-costa** [comment]
Brilliant, thank you very much! I didn't know about `vpath`, and this seems to work for me. Do you want me to update the PR accordingly?

**Comment by arjenmarkus** [comment]
As far as I know vpath is a feature supported by GNU make, but not
necessarily all flavours of make. Just be aware of it :).

Op ma 8 aug. 2022 om 01:19 schreef Pedro Costa ***@***.***>:

**Comment by awvwgk** [comment]
> As far as I know vpath is a feature supported by GNU make, but not necessarily all flavours of make. Just be aware of it :).

This is indeed a common issue with make. I can recommend to use fpm instead if you care for portability ;).

> Do you want me to update the PR accordingly?

Since we are currently migrating the webpage, having the patch on the new webpage would be much preferred (see #415).
