### ISSUE TITLE
Add packages from List-of-popular-open-source-Fortran-projects

### ISSUE THREAD

**Issue by certik** [fortran-lang/fortran-lang.org#68]
Go over:

https://github.com/fortran-lang/stdlib/wiki/List-of-popular-open-source-Fortran-projects

and add the rest of the packages.

**Comment by LKedward** [comment]
- [x] OpenBLAS
- [x] fortran-machine
- [x] LAPACK
- [x] ElmerFEM
- [x] WRF
- [x] fds
- [x] functional-fortran
- [x] Quantum ESPRESSO
- [x] fluidity
- [x] fortranlib
- [x] json-fortran
- [x] Nek5000
- [x] cp2k
- [x] fortran2018-examples
- [x] NASTRAN-95
- [ ] specfem3d
- [ ] NWChem
- [x] gtk-fortran
- [ ] CFL3D
- [x] fortran-utils
- [x] SHTOOLS
- [x] OpenCoarrays
- [x] arpack-ng
- [ ] DFTB+
- [ ] NASTRAN-93
- [ ] MPAS
- [x] neural-fortran
- [x] NetCDF-Fortran
- [ ] CTSM
- [x] Castro
- [x] ABINIT
- [x] FLAP
- [x] bspline-fortran
- [x] FOODIE
- [x] forpy
- [x] OFF
- [ ] WAVEWATCH III
- [ ] MOM6
- [x] VTKFortran
- [x] datetime-fortran
- [ ] node-fortran
- [ ] Fortran-Astrodynamics-Toolkit
- [x] pyplot-fortran
- [ ] Starlink
- [ ] WPS
- [x] ogpf
- [x] pFUnit
- [x] tcp-client-server
- [x] ftl
- [x] fgsl
- [ ] OpenCMISS
- [x] StringiFor
- [ ] wrf_hydro_nwm_public
- [x] SciFortran
- [ ] bandup
- [x] LaGriT
- [x] stdlib
- [x] clfortran
- [x] fox
- [ ] HANDE-QMC
- [x] FEconv
- [ ] lesgo
- [x] FortranPatterns
- [ ] FV3-GFS
- [x] coretran
- [ ] tsunami
- [x] fdict
- [ ] CFD
- [ ] ICAR
- [ ] MODFLOW6
- [ ] PIC Skeleton Codes
- [ ] IAMR
- [ ] ADflow
- [ ] PoisFFT
- [ ] sigma
- [ ] aenet
- [x] DBCSR
- [x] GALAHAD
- [ ] node.fortran
- [x] h5fortran
- [x] kdtree2
- [x] numerical-methods-fortran
- [ ] TRACMASS
- [ ] CompDam
- [ ] Flexi
- [ ] GFR
- [ ] OpenSWPC
- [ ] ROMS
- [x] slsqp
- [x] Truchas
- [x] fortran-csv-module
- [ ] FMS
- [ ] SNAP
- [x] freeCappuccino

**Comment by awvwgk** [comment]
Looks like there are 35 packages left. I had a quick look, but non is really in my field of expertise, so putting together useful tags would be difficult.

I think this could be a good opportunity for contributions, I will tag it with help-wanted to make it more visible.

**Comment by certik** [comment]
Thank you @awvwgk for your help with this. For volunteers who submit PRs for the remaining packages, don't be afraid to guess the relevant tags. We will do our best in the PR review. And if the upstream authors of the packages become interested in the future, they can always submit a PR to improve their entry.

**Comment by awvwgk** [comment]
I went through all the packages and opened https://github.com/fortran-lang/fortran-lang.org/pull/186 to add them to the package index. I removed projects by strikeout from the above list where I was unable to identify if the project is free open source software, this assessment might be incorrect for some projects (marked with *unclear license*), so feel free to double check those projects.
