### ISSUE TITLE
Tutorial: building compiled programs

### ISSUE THREAD

**Issue by LKedward** [fortran-lang/fortran-lang.org#77]
[As discussed on fortran-lang mailing list](https://groups.io/g/fortran-lang/topic/73954669?p=Created,,,20,1,0,0), this will cover compiling, linking and libraries.

Assigned: @arjenmarkus

**Comment by arjenmarkus** [comment]
I took the opportunity of a couple of hours during a lazy evening to sit down and write a quick-and-dirty document. No Markdown mark-up, just plain text. It is just the start, but it should illustrate what I am thinking of. Of course there are plenty of tools to help with building a program, but I think it is also important to understand what is going on when you build a program.

The document is very much work-in-progress, so have a look and et me know whether this is useful or not. 

[building_programs.txt](https://github.com/fortran-lang/fortran-lang.org/files/4636713/building_programs.txt)

**Comment by certik** [comment]
@arjenmarkus I think this looks great and I would like to have it in our Documentation section somewhere. @milancurcic, @LKedward where do you think would be the best place?

**Comment by milancurcic** [comment]
I love this. I think this is the kind of style we should take for tutorials. 

I think it would work well as a self-contained "book" (as described in #7) on building and linking, and we can link to it from the quickstart tutorial (/learn page). 

It will be straightforward to convert it to Markdown.

**Comment by LKedward** [comment]
Looks great, thanks @arjenmarkus.

**Comment by arjenmarkus** [comment]
Well, that is encouraging :).

Regards,

Arjen

Op vr 15 mei 2020 om 22:08 schreef Laurence Kedward <
notifications@github.com>:

**Comment by jvdp1** [comment]
@arjenmarkus Thank you for this manuscript. I really like the style.
It would be indeed easy to convert it to Markdown. We could help with the conversion when it will submitted to a PR.

**Comment by arjenmarkus** [comment]
Thanks - I am always a trifle uncertain about the precise formatting or the
dialect. Of course, so far the formatting requirements are very basic - and
I intend to keep it that way.

Regards,

Arjen

Op za 16 mei 2020 om 08:35 schreef Jeremie Vandenplas <
notifications@github.com>:

**Comment by arjenmarkus** [comment]
Short update: I have almost completed the draft of the tutorial I have in
mind. A rather tricky problem: make sure the _necessary_ details are
presented in a clear and structured way. It is easy enough to structure the
text and it is easy enough to describe all the details. But the challenge
is: only what is necessary in a structured way :).

Putting in the Markdown formatting was not a big issue, butI will probably
need some assistance with the next step - the pull request.

Regards,

Arjen

Op za 16 mei 2020 om 20:32 schreef Arjen Markus <arjen.markus895@gmail.com>:

**Comment by LKedward** [comment]
Thanks for the update @arjenmarkus.
Regarding the next step, I'm happy to provide guidance on putting together the PR or otherwise to submit the PR myself on your behalf.

**Comment by arjenmarkus** [comment]
Hi Laurence,

okay, I have finished the draft, converted it to Markdown and I have cloned
the website on my machine. I can simply add the file in the subdirectory
"learn", but I suppose I also need to add the header, like from the index:
---
layout: page
title: Quickstart Fortran
permalink: /learn/
navbar: Learn
---
but what to fill in?

Also: for now I have added a link to CC-BY, but is that the sort of license
we want to use for these mini-books? Or do we use LGPL or ...?

Regards,

Arjen
.

Op di 19 mei 2020 om 09:35 schreef Laurence Kedward <
notifications@github.com>:

**Comment by LKedward** [comment]
Hi @arjenmarkus,
Sounds good. Regarding the header, you only need to change the `title` field to the title of your tutorial
and the `permalink` field to something like `permalink: /learn/building_programs` - this will cause the web address of your tutorial to be `https://fortran-lang.org/learn/building_programs`. The ending after `/learn/` just needs to be a short descriptive string for your tutorial. The other fields (`layout`, `navbar`) can be kept the same as in the index file.

I'm not sure if we are using a different license for the tutorial content - the website _source_ is currently licensed under MIT, but it may be a good idea to license the tutorials under one of the CC-BY licenses. As the author and copyright holder, the licensing of the tutorial content is ultimately your choice - but it would be good to agree a license for all tutorial and similar content on fortran-lang.org. What are your thoughts @milancurcic and @certik ?

**Comment by certik** [comment]
I suggest to use an MIT license by default for such books. Consistent with other materials here. Unless the author specifically objects, in which case we can discuss on a case by case basis.

**Comment by LKedward** [comment]
> I suggest to use an MIT license by default for such books. Consistent with other materials here. Unless the author specifically objects, in which case we can discuss on a case by case basis.

I agree with preferring consistency, but MIT is strictly a software license - I believe the general copyright equivalent is CC-BY which simply requires attribution like MIT.

**Comment by certik** [comment]
I am not an expert on the CC licenses, I know some of them are not open source so we have to be very careful to pick the right one. What does Rust use for their documentation?

**Comment by certik** [comment]
P.S. I view documentation as code: it's written in Markdown, which literally is a source code that gets parsed and compiled to the final form, whether html or pdf. Also one can then copy and paste example code from the documentation into user projects without problem. So I've always used MIT for documentation.  But I am not opposed to other options.

**Comment by LKedward** [comment]
> I am not an expert on the CC licenses, I know some of them are not open source so we have to be very careful to pick the right one. 

Ah okay, good point - I'm no expert either.

> What does Rust use for their documentation?

[It appears to be under the same license as Rust itself which is MIT/Apache2](https://github.com/rust-lang/book/blob/master/CONTRIBUTING.md#licensing).


> P.S. I view documentation as code: it's written in Markdown, which literally is a source code that gets parsed and compiled to the final form, whether html or pdf. Also one can then copy and paste example code from the documentation into user projects without problem. So I've always used MIT for documentation. But I am not opposed to other options.

This makes sense to me; I'm happy to keep with MIT for consistency then :+1:

**Comment by arjenmarkus** [comment]
Hi everyone,

no problem with me - as long as it is a permissive licence :). The MIT
licence should do fine and consistency is not unimportance.

Regards,

Arjen

Op vr 22 mei 2020 om 16:44 schreef Laurence Kedward <
notifications@github.com>:

**Comment by certik** [comment]
Ok then, let's stick to MIT then.

**Comment by arjenmarkus** [comment]
Hi everyone,

I tried to view the new page as per the instructions via "jekyll", but I
got a lot of error messages:

$ bundle exec jekyll serve --watch
Configuration file: none
            Source: /cygdrive/d/fortran/fortran-lang/fortran-lang.org/learn
       Destination: /cygdrive/d/fortran/fortran-lang/
fortran-lang.org/learn/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
     Build Warning: Layout 'page' requested in best_practices.md does not
exist.
     Build Warning: Layout 'page' requested in building_programs.md does
not exist.
  Liquid Exception: Could not locate the included file 'note.html' in any
of ["/cygdrive/d/fortran/fortran-lang/fortran-lang.org/learn/_includes"].
Ensure it exists in one of those directories and, if it is a symlink, does
not point outside your site source. in index.md
jekyll 3.8.6 | Error:  Could not locate the included file 'note.html' in
any of ["/cygdrive/d/fortran/fortran-lang/fortran-lang.org/learn/_includes"].
Ensure it exists in one of those directories and, if it is a symlink, does
not point outside your site source.

I did a fresh install of Ruby, gems and bundle - there were some complaints
about old and deprecated packages, but nothing that seemed serious.

The file "note.html"  it is complaining about does actually exist in the
subdirectory _includes.

For your information: I installed Ruby and its packages on Cygwin.

Regards,

Arjen


Op vr 22 mei 2020 om 18:54 schreef Arjen Markus <arjen.markus895@gmail.com>:

**Comment by arjenmarkus** [comment]
Oh, now I see the problem - it looks at "learn/_includes", not "_includes".
Hm.

Regards,

Arjen

Op vr 22 mei 2020 om 20:03 schreef Arjen Markus <arjen.markus895@gmail.com>:

**Comment by certik** [comment]
@arjenmarkus did you figure it out?

I struggle with Jekyll too. See also #89.

**Comment by milancurcic** [comment]
@arjenmarkus we can also build a live preview from a pull request. Here's what you need to do:

1. Fork this repository
2. Clone your fork (not this repo), that would be https://github.com/arjenmarkus/fortran-lang.org
3. Add your content locally, commit it, then push to your repo on GitHub.
4. When you navigate back to this repo, there will be a button suggesting you to open a pull request
5. In pull request dialog, check the box that says "allow edits from reviewers" (or similar).

and we can make sure it previews correctly from there.

**Comment by arjenmarkus** [comment]
Hi everyone,

the problem was (apparently) that I started jekyll in the subdirectory
"learn" rather than the root. Now it works fine, that is. under "Learn" I
only see the contents of "index.md". I f I specify the paths
learn/best_practices and learn/build_programs I can see those pages. So,
accessing those pages is not entirely correct yet.

Well, with that solved and after a look at the page I will now proceed with
the pull request :).

Regards,

Arjen

Op vr 22 mei 2020 om 20:17 schreef Milan Curcic <notifications@github.com>:

**Comment by arjenmarkus** [comment]
Hi Milan, everyone,

I have now cloned the repository and created a branch
"building_programs". The pull request is there.

The repository is public, so I guess you can see it and submit your
comments etc. I hope I did all that correctly :).

Regards,

Arjen

Op vr 22 mei 2020 om 20:17 schreef Milan Curcic <notifications@github.com>:

**Comment by milancurcic** [comment]
Almost there. It looks like you created a pull request in your own repository (arjenmarkus/fortran-lang.org). 

Instead, create a pull request in [this repository](https://github.com/fortran-lang/fortran-lang.org) (fortran-lang/fortran-lang.org) by navigating to its home page and clicking on the "New pull request" button.

I don't know if this matters, but I also see that your fortran-lang.org repository doesn't appear as a fork. Did you create it by clicking the "Fork" button on this repository?

**Comment by arjenmarkus** [comment]
Hi Milan,

I thought I had created a fork. Hm, let me redo that. (It does not seem
possible to create a pull request based on the one I just created).
Hopefully I will get it right this time.

Regards,

Arjen

Op vr 22 mei 2020 om 21:06 schreef Milan Curcic <notifications@github.com>:

**Comment by arjenmarkus** [comment]
No, I had created a repository in my personal space and imported the
fortran-lang.org repository. What I should have done is go to the home page
of fortran-lang.org and use the "Fork" option from there. Well, hopefully
it is all right now :). I think this will be the last e-mail from me for
today.

Regards,

Arjen

Op vr 22 mei 2020 om 21:11 schreef Arjen Markus <arjen.markus895@gmail.com>:

**Comment by milancurcic** [comment]
@arjenmarkus Yes, that worked! Thank you! I will review it in detail over the weekend.

**Comment by LKedward** [comment]
Closing, completed by #99.
